spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "http://localhost:9200/logout"
            assertingparty:
              metadata-uri: "classpath:metadata/metadata-idp.xml"

server:
  port: 9200